/*
 @name : 锅巴汉化 - Web汉化插件
 @author : 麦子、JAR、小蓝、好阳光的小锅巴、人民當家做主
 @version : V0.6.5 - 2026-7-7
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
*/

// ============================================================
// 匹配配置
// ============================================================
// ignoreCase: true   忽略大小写(Gold/gold/GOLD都匹配), false=区分大小写
// trimSpaces: true   忽略首尾空格(" gold "匹配"gold"), false=保留空格
//
// 影响范围：
//   ✅ cnItems 精确匹配(字符串值+数组值)
//   ✅ cnItems 分类索引({{分类名}}/{{分类名*}}/{{分类名*|sep|join}})
//   ✅ cnResourceNames 名词翻译
//   ✅ cnPrefix / cnPostfix 前后缀
//   ✅ cnRegReplace / 排除规则 / 模板正则(通过 addIgnoreCaseFlag / cnConfig.ignoreCase 控制)
var cnConfig = {
    ignoreCase: true,
    trimSpaces: true,
};

// ============================================================
// cnCategoriesList — 分类名称注册表（供编辑器工具使用）
// ============================================================
// 分类数据由 cnItems 中的数组值 ["译文", "分类名"] 自动构建。
// 此列表仅声明有哪些分类，以便编辑器提供分类选择/管理功能。
var cnCategoriesList = [
    "resource",
    "item",
];

// ============================================================
// cnItems — 主要翻译词条
// ============================================================
// 用法：
//   "原文": "译文"                         → 精确静态匹配
//   "原文": ["译文", "分类名"]               → 静态匹配 + 自动加入分类
//   "Cost: {{0}}": "消耗：{{0}}"            → 模板匹配 ({{0}} 匹配任意值)
//   "{{resource}}: {{%d}}": "{{resource}}：{{%d}}"  → 分类模板 + 数字验证
//   "{{分类名*}}": 仅在该分类查找，找不到保留原文
//   "{{分类名*|sep|join}}": 分类限定列表解析
//   "{{*}}": 通用列表，逐项递归翻译
//   "{{*|sep|join}}": 自定义分隔符/连接词的列表
// ============================================================
var cnItems = {
    // --- 静态匹配 ---
    "Welcome": "欢迎",
    "Score": "分数",
    "Health Potion": "生命药水",
    "Hello World": "你好世界",
    "Settings": "设置",

    // --- 分类词条 [译文, 分类名] ---
    "gold": ["金币", "resource"],
    "wood": ["木材", "resource"],
    "stone": ["石头", "resource"],
    "iron": ["铁", "resource"],
    "sword": ["剑", "item"],
    "shield": ["盾牌", "item"],
    "helmet": ["头盔", "item"],

    // --- 模板 ({{0}} / {{1}}) ---
    "Cost: {{0}}": "消耗：{{0}}",
    "Next Improvement: {{0}}": "下次提升：{{0}}",
    "Level {{0}}": "等级{{0}}",
    "{{0}} x {{1}}": "{{0}} × {{1}}",

    // --- 模板 ({{分类名}} + {{%d}}) ---
    "{{resource}}: {{0}}": "{{resource}}：{{0}}",

    // --- 模板 ({{分类名*}} 仅分类) ---
    "Get {{0}} {{resource*}}": "获得 {{0}} {{resource*}}",

    // --- 模板 ({{分类名*|sep|join}} 分类列表) ---
    "Craft {{item*|,|和}}": "制作{{item*|,|和}}",

    // --- 通用列表 {{*}} / {{*|sep|join}} ---
    "Items: {{*}}": "物品：{{*}}",
    "Mats: {{*|, |、}}": "材料：{{*|, |、}}",

    // --- 数字占位符 {{%d}} ---
    "HP: {{%d}}": "生命值：{{%d}}",
    "DMG: {{%d}}": "伤害：{{%d}}",

    " · Coal":" · 煤",
    " Accept ":"接受",
    " Achievements ":"成就",
    " Blueprints ":"蓝图",
    " Decline ":"拒绝",
    " Hub ":"枢纽",
    " Recipes ":"配方",
    " Reset ":"重置",
    " Save data ":"存档",
    " This game works without it. If you say yes, Google Analytics gets a cookie on this device so I can see how many people play and where they get stuck. ":"这个游戏在没有它的前提下也能运行。如果你选择“是”，Google Analytics 就会在你的设备上放置一个 Cookie，以便我了解有多少人参与游戏以及他们在哪些地方卡住了。",
    " Tutorial ":" 教程 ",
    " Upgrades ":"分析？",
    "Analytics?":"组装机",
    "Assembler":"组装机",
    "Banked":"已存储",
    "Belt":"传送带",
    "Blueprint":"蓝图",
    "Bulldoze":"拆除",
    "Circuit":"电路",
    "Coal":"煤",
    "Copper Ore":"铜矿石",
    "Copper Plate":"铜板",
    "Furnace":"熔炉",
    "Gear":"齿轮",
    "Hub":"枢纽",
    "Inspect":"检视",
    "Iron Ore":"铁矿",
    "Iron Plate":"铁板",
    "Miner":"采矿机",
    "Motor":"马达",
    "Plastic":"塑料",
    "Power Pole":"电线杆",
    "Processor":"处理器",
    "Research Core":"研究核心",
    "Steel":"钢",
    "Titanium Ore":"钛矿石",
    "Titanium Plate":"钛板",
    "What is collected":"已收集物品",
    "saved now":"已保存",
    "empty":"空",
    " Collect ":" 收集 ",
    " Offline pay comes from what actually reaches the Hub. Route a belt into it and the rate you leave on is the rate you are paid for. ":"离线收益取决于实际输送到枢纽的物资。将传送带接入枢纽，你维持的输送速率就是结算收益的速率。",
    "Welcome back":"欢迎回来",
    "Your factory earned nothing.":"你的工厂没有产生任何收益。",
    " · Iron Ore":"· 铁矿",
    "Merger":"合并器",
    "Mergers":"合并器",
    "Puller":"拉取器",
    "Pullers":"拉取器",
    "Pusher":"推送器",
    "Pushers":"推送器",
    "Splitter":"分流器",
    "Splitters":"分流器",
    "Tunnel Entry":"隧道入口",
    "Tunnels":"隧道",
    "locked":"已锁定",
    " · Copper Ore":"· 铜矿",
    "Copy":"复制",
    "Remove":"移除",
    "Turn":"切换",
    "Controls (?)":"控制 (?)",
    " Next ▶ ":" 下一步 ▶ ",
    " ◀ Back ":" ◀ 返回 ",
    " Skip ":" 跳过 ",
    " places an entry on the first click and its exit on the second, inside the highlighted range. Items run under everything between, and only that entry feeds that exit ":"在高亮范围内，第一次点击放置隧道入口，第二次点击放置出口。物品从两者之间所有物体下方穿行，且仅该入口向对应出口输送物资。",
    " - a pole wires everything in its radius, poles included. Generators burn coal into charge and batteries hold it; a generator with no battery behind it burns nothing ":"- 电线杆会连通其范围内所有物体，包括其他电线杆。发电机将煤炭转化为电力，电池用于储存电力；发电机后方若无电池，则不会消耗煤炭。",
    "Click the Miner slot in the toolbar (or press 2), then place it on the ringed ore patch. It fills itself, no fuel needed. R rotates the ghost first, or use the arrow button bottom right, if you want its output facing a particular way.":"点击工具栏中的采矿机图标（或按快捷键2），然后将其放置在带圈的矿点上。采矿机会自动装填，无需燃料。如果想调整输出朝向，可以先按R旋转预览虚影，或是使用右下角方向按钮。",
    "Space + left drag":"空格键 + 左键 拖拽",
    "Controls":"控制",
    "Camera":"相机",
    "Left drag":"左键 拖拽",
    "Left drag (Bulldoze)":"左键 拖拽 (拆除)",
    "Right click":"右击",
    "Dig ore":"挖掘矿石",
    "Needs":"要求",
    "Electric Furnace":"电炉",
    "Electric Smelting":"电力冶炼",
    "Deep Drill":"深层钻机",
    "Deep Drilling":"深层钻探",
    "Electric Miner":"电动采矿机",
    "Electric Mining":"电力开采",
    "Chemical Plant":"化工厂",
    "Electric Assembler":"电力组装机",
    "Electric Assembly":"电力组装",
    "Petrochemistry":"石油化工",
    "Research Lab":"研究实验室",
    "Research Labs":"研究实验室（复数）",
    "Battery":"电池",
    "Beacon":"信标",
    "Beacons":"信标（复数）",
    "Coal Generator":"燃煤发电机",
    "Electrification":"电气化",
    "Drafting Office":"制图室",
    "on Copper Ore":"作用于铜矿",
    " Worth ":"价值",
    " delivered. You have ":"已输送。你拥有",
    " what makes it, and what it is for ":"它的制作原料，以及它的用途",
    "Conveyor Logic":"传送带逻辑",
    "Feeds":"供给",
    "Fuel Efficiency":"燃料效率",
    "Furnace Speed":"熔炉速度",
    "Made by":"制作方",
    "Pays for":"产出回报",
    "Pole Reach":"电线杆覆盖范围",
    " Mined. Put a miner on a patch of it. ":"可开采。在矿点放置采矿机。",
    " Burns as fuel.":"可作为燃料燃烧。",
    "Battery ":"电池",
    "Belt Speed":"传送带速度",
    "Builds":"可建造",
    "Chemical Plant ":"化工厂",
    "Coal Generator ":"燃煤发电机",
    "Drill Speed":"钻机速度",
    "Electric Assembler ":"电力组装机",
    "Electric Furnace ":"电炉",
    "Electric Miner ":"电动采矿机",
    "Firebox":"燃烧室深入地下",
    "Land Survey":"土地勘测同时运行一百台机器。",
    "Ore Bins":"矿石仓一分钟内保持每秒获得五十点分数。",
    "Ore Hoppers":"矿石料斗扭亏为盈",
    "Part Bins":"零件仓工业家",
    "Tunnel Exit ":"隧道出口同时维持五座熔炉燃烧。",
    "Assembler Speed":"组装机速度持续供给二十台组装机。",
    "Deep Bore":"深层钻探维持二十座熔炉运转。",
    "Drill Yield":"钻机产出铺设二十五格传送带。",
    "Filter Splitters":"过滤分流器铺设两百格传送带。",
    "Night Shift":"夜班大规模生产",
    "Battery Banks":"电池组传送带之上",
    "Deep Drill ":"深层钻机露天矿场",
    "Express Lanes":"高速通道同时拥有二十五级升级。",
    "Heat Exchanger":"热交换器放置四个分流器。",
    "Hub Logistics":"枢纽物流轧板厂",
    "Precision Tools":"精密工具板材盈余",
    "Requisition Rate":"申领速率分数达到十万。",
    "Trade Network":"贸易网络分数达到一千。",
    "Beacon ":"信标研究预算",
    "Research Lab ":"研究实验室同时运行五台组装机。",
    "Catalysts":"催化剂同时运行五座化工厂。",
    "Beacon Field":"信标场利用隧道，在同一设施下方运行四条产线。",
    "Beacon Tuning":"信标调谐工厂累计运行一小时。",
    " Milestones pay a small permanent bonus each, on top of the upgrade tree. Nothing is spent to earn one, and nothing takes one back. ":"里程碑每项都会提供少量永久加成，独立于升级树。达成无需消耗资源，且加成不会被收回。同时启用二十台采矿机。",
    "Bank a thousand iron plate.":"储备一千块铁板。冶炼产线",
    "Bank five hundred coal.":"储备五百煤炭。分拣办公室",
    "Bank five thousand iron plate at once.":"一次性储备五千块铁板。物资储备",
    "Bank two hundred and fifty circuits.":"储备两百五十个电路。同时开采五处矿点。",
    "Belt Baron":"传送带大亨组装",
    "Circuit City":"电路之城消耗",
    "Coal Cellar":"煤炭地窖物流",
    "Completionist":"全收集者采矿",
    "Conglomerate":"联合企业电力",
    "Cracking Plant":"裂解工厂重置视角",
    "Deliver a hundred iron plates a second, averaged over a full minute.":"一分钟平均每秒输送一百块铁板。出售升级等级可全额返还资源，不会因为购买升级导致存档卡死。",
    "Drill Team":"钻探小队冶炼",
    "Earn fifteen other achievements.":"解锁十五项其他成就。永久生效且作用于整个工厂，可全额折价回售",
    "Flow State":"流畅运转组装机速度",
    "Foundry":"铸造厂电池组",
    "Beacon Field ":"信标场",
    "Beacon Tuning ":"信标调谐",
    "Beacons ":"信标",
    "Belt Speed ":"传送带速度",
    "Catalysts ":"催化剂",
    "Conveyor Logic ":"传送带逻辑",
    "Deep Bore ":"深层钻探",
    "Drafting Office ":"制图室",
    "Drill Speed ":"钻机速度",
    "Drill Yield ":"钻机产出",
    "Electric Assembly ":"电力组装",
    "Electric Mining ":"电力开采",
    "Electric Smelting ":"电力冶炼",
    "Electrification ":"电气化",
    "Express Lanes ":"高速通道",
    "Factory upgrades":"工厂升级",
    "Filter Splitters ":"过滤分流器",
    "Firebox ":"燃烧室",
    "Fuel Efficiency ":"燃料效率",
    "Furnace Speed ":"熔炉速度",
    "Heat Exchanger ":"热交换器",
    "Hub Logistics ":"枢纽物流",
    "Land Survey ":"土地勘测",
    "Level":"等级",
    "Miners cycle faster.":"采矿机运转更快。",
    "Mining T1":"一级采矿",
    "Next level":"下一级",
    "Night Shift ":"夜班",
    "Ore Bins ":"矿石仓",
    "Ore Hoppers ":"矿石料斗",
    "Part Bins ":"零件仓",
    "Petrochemistry ":"石油化工",
    "Pole Reach ":"电线杆覆盖范围",
    "Precision Tools ":"精密工具",
    "Requisition Rate ":"申领速率",
    "Research Labs ":"研究实验室",
    "Trade Network ":"贸易网络",
    "drag to pan, pinch to zoom":"拖拽平移，双指缩放",
    "drag to pan, scroll to zoom":"拖拽平移，滚轮缩放",
    "Items travel further each tick.":"物品每帧移动距离更远。",
    " when unlocked":"解锁时",
    "+0.4% Miner speed per Belt, max +20%":"每条传送带提升采矿机速度0.4%，最高+20%",
    "Miners run faster the more belt you have laid.":"铺设的传送带越多，采矿机运转越快。",
    "Unlocks the splitter":"解锁分流器",
    "one lane in, three lanes out in turn.":"单入口，循环向三个出口输送物料。",
    "Smelting finishes sooner. Coal per smelt is unchanged.":"冶炼完成速度提升。单次冶炼煤炭消耗不变。",
    "Crafts finish sooner.":"制作完成速度提升。",
    " The book is closed. Buy ":"手册已关闭。",
    " in the upgrade tree to open it; every level after the first adds another page. ":"在升级树中购买解锁；每提升一级，新增一页内容。",
    "A stamp is charged like building by hand, lands only on surveyed ground, and places whatever fits":"印记放置的资源消耗和手动建造一致，仅可在已勘测的土地上使用，放置范围内可容纳的建筑会生成；",
    "what will not fit is reported instead of cancelling the rest.":"无法放置的内容会单独提示，其余建筑不会取消。",
    " - open a machine to set its recipe; drag still pans ":"- 点开机器设置配方；拖拽仍可平移视角",
    " - pan":"- 平移视角",
    " - pan, or right / middle drag":"- 平移视角，或右键/中键拖拽",
    " - pick a toolbar slot. Press the active one again, or ":"- 选中工具栏项目。再次点击当前选中项，或者",
    " - place; belts auto-connect along the drag":"- 放置建筑；拖拽时传送带自动连接",
    " - remove one building instantly, fully refunded; works with any tool selected ":"- 立即拆除单个建筑，全额返还资源；任意工具状态下均可使用",
    " - select an area, then confirm. Removal always refunds the full cost plus anything held inside ":"- 框选区域，随后确认。拆除将全额返还建造资源以及建筑内留存物资",
    " - the red wash is ground you have not surveyed. Buy Land Survey in the upgrade tree to double the square you can build on ":"- 红色区域代表未勘测土地。在升级树购买土地勘测，可将可建造区域扩大一倍",
    " - turn the building under the cursor; over bare ground it turns the ghost instead (":"- 旋转光标下的建筑；在空地时仅旋转预览虚影",
    " - zoom, ":"- 缩放视角",
    " Anonymous usage analytics are off, and nothing is stored for them. ":"匿名使用统计已关闭，不会留存相关数据。",
    " Miners dig ore, belts carry it, the Hub banks it. Everything below is optional. ":"采矿机开采矿石，传送带运送物资，枢纽负责存储。下方所有内容均为可选。",
    " Your save lives in this browser and there is no account. ":"存档保存在当前浏览器，无需账号。",
    " push out of their marked edge into the tile they face, and miners only sit on ore. Route anything into the Hub to bank it ":"从标记边缘推送物资至朝向地块，采矿机仅能放置在矿点上。将物资输送至枢纽即可存入仓库。",
    " puts it back ":"放回原位",
    " reverses) ":"反向运作",
    " takes from behind and sends items out left, ahead and right in turn; a merger does the reverse. Both are belts as far as upgrades care ":"从后方拾取物料，依次向左、向前、向右输出；合并器功能与之相反。在升级效果判定上，二者均视作传送带。",
    " turns the stamp, ":"旋转印记，",
    ", to drop back to inspect ":"回到查看模式",
    "- achievements":"- 成就",
    "- blueprints":"- 蓝图",
    "- copy the building under the cursor":"- 复制光标下的建筑",
    "- the recipe book":"- 配方手册",
    "- the upgrade tree":"- 升级树",
    "Build and remove":"建造与拆除",
    "Inspect + click":"查看 + 点击",
    "Land":"土地",
    "Machines":"机器",
    "Panels":"面板",
    "Power":"电力",
    "Privacy.":"隐私设置",
    "Shapes and ground":"地形与地块",
    "Shift+R":"Shift+R",
    "Tunnel":"隧道",
    "Turn analytics on":"开启统计分析",
    "Wheel":"滚轮",
    "drag an area to copy it into the book. A page in hand stamps on a click and still copies on a drag.":"框选区域，可将其复制到手册中。手持手册页面时，单击进行印记放置，拖拽依旧可以复制区域。",
    "facing and recipe come with it":"朝向与配方一并复制",
    "milestones that each pay a small permanent bonus, earned once and never lost":"里程碑：每项提供少量永久加成，达成一次即可获得，永久保留",
    "permanent, factory-wide bonuses bought with banked items, sellable back at full price":"使用储备物资购买的全局工厂永久加成，可全额回售",
    "what makes what, and out of what":"物品产出关系，以及所需原料",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "关注新公众号": "关注新公众号",
    "打开微信扫一扫": "打开微信扫一扫",
    "游戏攻略交流论坛": "游戏攻略交流论坛",
    "点击加群": "点击加群",
    "锅巴汉化": "锅巴汉化",
    "WASD": "WASD",
    " (E)": " (E)",
    "Esc": "Esc",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "x": "x",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    
};
// ============================================================
// cnResourceNames — 资源名词翻译（备用，优先级低于 cnItems）
// ============================================================
// 支持 "名词: 数值" 格式的自动翻译（如 "Mana: 500" → "法力：500"）
var cnResourceNames = {};
// cnRegReplace — 正则替换（备用，优先级低于精确匹配但高于模板/分类）
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^ Away (.+) min. $/, ' 离开了 $1 分钟。'],
    [/^ Objective (.+)$/, ' 目标 $1 '],
    [/^(.+) ticks played$/, '进行游戏 $1 tick'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)s$/, '$1秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Chemical Plant · ([\d\.]+)s$/, '化工厂 · $1 秒'],
    [/^Research Lab · ([\d\.]+)s$/, '研究实验室 · $1 秒'],
    [/^Assembler · ([\d\.]+)s$/, '组装机 · $1 秒'],
    [/^Furnace · ([\d\.]+)s$/, '熔炉 · $1 秒'],
    [/^ \+([\d\.]+)\/s $/, ' +$1/秒 '],
    [/^\+([\d\.]+)\% Splitter unlocked$/, '+$1% 分流器 解锁'],
    [/^\+([\d\.]+)\% speed$/, '+$1% 速度'],
    [/^\+([\d\.]+)\% Miner speed$/, '+$1% 采矿机 速度'],
    [/^\+([\d\.]+)\% Furnace speed$/, '+$1% 熔炉 速度'],
    [/^\+([\d\.]+)\% Belt speed$/, '+$1% 传送带 速度'],
    [/^\+([\d\.]+)\% Miner speed$/, '+$1% 采矿机 速度'],
    [/^\+([\d\.]+)\% Chemical Plant speed$/, '+$1% 化工厂 速度'],
    [/^\+([\d\.]+)\% Assembler speed$/, '+$1% 组装机 速度'],
    [/^\+([\d\.]+)\% fuel burn time$/, '+$1% 燃料燃烧时间'],
    [/^\+([\d\.]+)\% offline rate$/, '+$1% 离线效率'],
    [/^\+([\d\.]+)\% item value$/, '+$1% 物品价值'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) score$/, '$1 分数'],
    [/^([\d\.,]+) Iron Plate$/, '$1 铁板'],
    [/^([\d\.,]+) Iron Plate, ([\d\.,]+) Gear$/, '$1 铁板, $2 齿轮'],
    [/^([\d\.,]+) Furnace placed$/, '放置 $1 熔炉'],
    [/^([\d\.,]+) Tunnel Entry placed$/, '放置 $1 隧道入口'],
    [/^([\d\.,]+) Assembler placed$/, '放置 $1 组装机'],
    [/^([\d\.,]+) Belt placed$/, '放置 $1 传送带'],
    [/^([\d\.,]+) machines placed$/, '放置 $1 机器'],
    [/^([\d\.,]+) Splitter placed$/, '放置 $1 分流器'],
    [/^([\d\.,]+) Miner placed$/, '放置 $1 采矿机'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Miner placed$/, '放置 $1 \/ $2 采矿机'],
    [/^([\d\.,]+) Chemical Plant placed$/, '放置 $1 化工厂'],
    [/^([\d\.,]+) Coal banked$/, '存储 $1 煤'],
    [/^([\d\.,]+) Circuit banked$/, '存储 $1 电路'],
    [/^([\d\.,]+) Iron Plate banked$/, '存储 $1 铁板'],
    [/^([\d\.,]+) Iron Plate per second$/, '每秒 $1 铁板'],
    [/^([\d\.,]+) score per second$/, '每秒 $1 分'],
    [/^([\d\.,]+) achievements earned$/, '解锁 $1 成就'],
    [/^([\d\.,]+) upgrade levels owned$/, '拥有 $1 升级等级'],
    [/^([\d\.,]+) Research Core$/, '$1 研究核心'],
    [/^([\d\.,]+) Circuit$/, '$1 电路'],
    [/^([\d\.,]+) Titanium Ore$/, '$1 钛矿石'],
    [/^([\d\.,]+) Copper Ore$/, '$1 铜矿石'],
    [/^([\d\.,]+) Iron Ore$/, '$1 铁矿石'],
    [/^([\d\.,]+) Copper Plate$/, '$1 铜板'],
    [/^([\d\.,]+) Iron Plate$/, '$1 铁板'],
    [/^([\d\.,]+) Titanium Plate$/, '$1 钛板'],
    [/^([\d\.,]+) Plastic$/, '$1 塑料'],
    [/^([\d\.,]+) Coal$/, '$1 煤'],
    [/^([\d\.,]+) Steel$/, '$1 钢'],
    [/^([\d\.,]+) Motor$/, '$1 马达'],
    [/^([\d\.,]+) Gear$/, '$1 齿轮'],
    [/^([\d\.,]+) Processor$/, '$1 处理器'],
    [/^([\d\.,]+) Plastic$/, '$1 塑料'],
    [/^([\d\.,]+) lv $/, '$1 等级 '],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^saved ([\d\.,]+)s$/, '已保存 $1秒'],
    [/^saved ([\d\.,]+)m$/, '已保存 $1分'],
    [/^levels ([\d\.,]+)\-([\d\.,]+)$/, '等级 $1-$2'],
    [/^ Install level ([\d\.,]+)$/, ' 安装等级 $1'],
    [/^have ([\d\.,]+)$/, '拥有 $1'],
    [/^Belt Speed ([\d\.,]+)$/, '传送带 速度 $1'],
    [/^Assembly T([\d\.,]+)$/, '装配 T$1'],
    [/^Smelting T([\d\.,]+)$/, '冶炼 T$1'],
    [/^Logistics T([\d\.,]+)$/, '物流 T$1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Step (.+) of (.+)$/, '步骤 $1 \/ $2'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
]);
// 前缀/后缀提取（备用）
var cnPrefix = {
    ": ": "： ",
};
var cnPostfix = {
    ":": "：",
};
// 排除规则
var cnExcludeWhole = [
    /^([\d\.]+) fps$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
];
var cnExcludePostfix = [];
