/*
 @name : 锅巴汉化 - Web汉化插件
 @author : 麦子、JAR、小蓝、好阳光的小锅巴、人民當家做主
 @version : V0.6.5 - 2026-7-7
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
*/

// ============================================================
// 匹配配置
// ============================================================
// ignoreCase: true   忽略大小写(Gold/gold/GOLD都匹配), false=区分大小写
// trimSpaces: true   忽略首尾空格(" gold "匹配"gold"), false=保留空格
//
// 影响范围：
//   ✅ cnItems 精确匹配(字符串值+数组值)
//   ✅ cnItems 分类索引({{分类名}}/{{分类名*}}/{{分类名*|sep|join}})
//   ✅ cnResourceNames 名词翻译
//   ✅ cnPrefix / cnPostfix 前后缀
//   ✅ cnRegReplace / 排除规则 / 模板正则(通过 addIgnoreCaseFlag / cnConfig.ignoreCase 控制)
var cnConfig = {
    ignoreCase: true,
    trimSpaces: true,
};

// ============================================================
// cnCategoriesList — 分类名称注册表（供编辑器工具使用）
// ============================================================
// 分类数据由 cnItems 中的数组值 ["译文", "分类名"] 自动构建。
// 此列表仅声明有哪些分类，以便编辑器提供分类选择/管理功能。
var cnCategoriesList = [
    "resource",
    "item",
];

// ============================================================
// cnItems — 主要翻译词条
// ============================================================
// 用法：
//   "原文": "译文"                         → 精确静态匹配
//   "原文": ["译文", "分类名"]               → 静态匹配 + 自动加入分类
//   "Cost: {{0}}": "消耗：{{0}}"            → 模板匹配 ({{0}} 匹配任意值)
//   "{{resource}}: {{%d}}": "{{resource}}：{{%d}}"  → 分类模板 + 数字验证
//   "{{分类名*}}": 仅在该分类查找，找不到保留原文
//   "{{分类名*|sep|join}}": 分类限定列表解析
//   "{{*}}": 通用列表，逐项递归翻译
//   "{{*|sep|join}}": 自定义分隔符/连接词的列表
// ============================================================
var cnItems = {
    // --- 静态匹配 ---
    "Welcome": "欢迎",
    "Score": "分数",
    "Health Potion": "生命药水",
    "Hello World": "你好世界",
    "Settings": "设置",

    // --- 分类词条 [译文, 分类名] ---
    "gold": ["金币", "resource"],
    "wood": ["木材", "resource"],
    "stone": ["石头", "resource"],
    "iron": ["铁", "resource"],
    "sword": ["剑", "item"],
    "shield": ["盾牌", "item"],
    "helmet": ["头盔", "item"],

    // --- 模板 ({{0}} / {{1}}) ---
    "Cost: {{0}}": "消耗：{{0}}",
    "Next Improvement: {{0}}": "下次提升：{{0}}",
    "Level {{0}}": "等级{{0}}",
    "{{0}} x {{1}}": "{{0}} × {{1}}",

    // --- 模板 ({{分类名}} + {{%d}}) ---
    "{{resource}}: {{0}}": "{{resource}}：{{0}}",

    // --- 模板 ({{分类名*}} 仅分类) ---
    "Get {{0}} {{resource*}}": "获得 {{0}} {{resource*}}",

    // --- 模板 ({{分类名*|sep|join}} 分类列表) ---
    "Craft {{item*|,|和}}": "制作{{item*|,|和}}",

    // --- 通用列表 {{*}} / {{*|sep|join}} ---
    "Items: {{*}}": "物品：{{*}}",
    "Mats: {{*|, |、}}": "材料：{{*|, |、}}",

    // --- 数字占位符 {{%d}} ---
    "HP: {{%d}}": "生命值：{{%d}}",
    "DMG: {{%d}}": "伤害：{{%d}}",

    " · Coal":" · 煤",
    " Accept ":"接受",
    " Achievements ":"成就",
    " Blueprints ":"蓝图",
    " Decline ":"拒绝",
    " Hub ":"枢纽",
    " Recipes ":"配方",
    " Reset ":"重置",
    " Save data ":"存档",
    " This game works without it. If you say yes, Google Analytics gets a cookie on this device so I can see how many people play and where they get stuck. ":"这个游戏在没有它的前提下也能运行。如果你选择“是”，Google Analytics 就会在你的设备上放置一个 Cookie，以便我了解有多少人参与游戏以及他们在哪些地方卡住了。",
    " Tutorial ":" 教程 ",
    " Upgrades ":"分析？",
    "Analytics?":"组装机",
    "Assembler":"组装机",
    "Banked":"已存储",
    "Belt":"传送带",
    "Blueprint":"蓝图",
    "Bulldoze":"拆除",
    "Circuit":"电路",
    "Coal":"煤",
    "Copper Ore":"铜矿石",
    "Copper Plate":"铜板",
    "Furnace":"熔炉",
    "Gear":"齿轮",
    "Hub":"枢纽",
    "Inspect":"检视",
    "Iron Ore":"铁矿",
    "Iron Plate":"铁板",
    "Miner":"采矿机",
    "Motor":"马达",
    "Plastic":"塑料",
    "Power Pole":"电线杆",
    "Processor":"处理器",
    "Research Core":"研究核心",
    "Steel":"钢",
    "Titanium Ore":"钛矿石",
    "Titanium Plate":"钛板",
    "What is collected":"已收集物品",
    "saved now":"已保存",
    "empty":"空",
    " Collect ":" 收集 ",
    " Offline pay comes from what actually reaches the Hub. Route a belt into it and the rate you leave on is the rate you are paid for. ":"离线收益取决于实际输送到枢纽的物资。将传送带接入枢纽，你维持的输送速率就是结算收益的速率。",
    "Welcome back":"欢迎回来",
    "Your factory earned nothing.":"你的工厂没有产生任何收益。",
    " · Iron Ore":"· 铁矿",
    "Merger":"合并器",
    "Mergers":"合并器",
    "Puller":"拉取器",
    "Pullers":"拉取器",
    "Pusher":"推送器",
    "Pushers":"推送器",
    "Splitter":"分流器",
    "Splitters":"分流器",
    "Tunnel Entry":"隧道入口",
    "Tunnels":"隧道",
    "locked":"已锁定",
    " · Copper Ore":"· 铜矿",
    "Copy":"复制",
    "Remove":"移除",
    "Turn":"切换",
    "Controls (?)":"控制 (?)",
    " Next ▶ ":" 下一步 ▶ ",
    " ◀ Back ":" ◀ 返回 ",
    " Skip ":" 跳过 ",
    " places an entry on the first click and its exit on the second, inside the highlighted range. Items run under everything between, and only that entry feeds that exit ":"在高亮范围内，第一次点击放置隧道入口，第二次点击放置出口。物品从两者之间所有物体下方穿行，且仅该入口向对应出口输送物资。",
    " - a pole wires everything in its radius, poles included. Generators burn coal into charge and batteries hold it; a generator with no battery behind it burns nothing ":"- 电线杆会连通其范围内所有物体，包括其他电线杆。发电机将煤炭转化为电力，电池用于储存电力；发电机后方若无电池，则不会消耗煤炭。",
    "Click the Miner slot in the toolbar (or press 2), then place it on the ringed ore patch. It fills itself, no fuel needed. R rotates the ghost first, or use the arrow button bottom right, if you want its output facing a particular way.":"点击工具栏中的采矿机图标（或按快捷键2），然后将其放置在带圈的矿点上。采矿机会自动装填，无需燃料。如果想调整输出朝向，可以先按R旋转预览虚影，或是使用右下角方向按钮。",
    "Space + left drag":"空格键 + 左键 拖拽",
    "Controls":"控制",
    "Camera":"相机",
    "Left drag":"左键 拖拽",
    "Left drag (Bulldoze)":"左键 拖拽 (拆除)",
    "Right click":"右击",
    "Dig ore":"挖掘矿石",
    "Needs":"要求",
    "Electric Furnace":"电炉",
    "Electric Smelting":"电力冶炼",
    "Deep Drill":"深层钻机",
    "Deep Drilling":"深层钻探",
    "Electric Miner":"电动采矿机",
    "Electric Mining":"电力开采",
    "Chemical Plant":"化工厂",
    "Electric Assembler":"电力组装机",
    "Electric Assembly":"电力组装",
    "Petrochemistry":"石油化工",
    "Research Lab":"研究实验室",
    "Research Labs":"研究实验室",
    "Battery":"电池",
    "Beacon":"信标",
    "Beacons":"信标",
    "Coal Generator":"燃煤发电机",
    "Electrification":"电气化",
    "Drafting Office":"制图室",
    "on Copper Ore":"作用于铜矿",
    " Worth ":"价值",
    " delivered. You have ":"已输送。你拥有",
    " what makes it, and what it is for ":"它的制作原料，以及它的用途",
    "Conveyor Logic":"传送带逻辑",
    "Feeds":"供给",
    "Fuel Efficiency":"燃料效率",
    "Furnace Speed":"熔炉速度",
    "Made by":"制作方",
    "Pays for":"产出回报",
    "Pole Reach":"电线杆覆盖范围",
    " Mined. Put a miner on a patch of it. ":"可开采。在矿点放置采矿机。",
    " Burns as fuel.":"可作为燃料燃烧。",
    "Battery ":"电池",
    "Belt Speed":"传送带速度",
    "Builds":"可建造",
    "Chemical Plant ":"化工厂",
    "Coal Generator ":"燃煤发电机",
    "Drill Speed":"钻机速度",
    "Electric Assembler ":"电力组装机",
    "Electric Furnace ":"电炉",
    "Electric Miner ":"电动采矿机",
    "Firebox":"燃烧室深入地下",
    "Land Survey":"土地勘测同时运行一百台机器。",
    "Ore Bins":"矿石仓一分钟内保持每秒获得五十点分数。",
    "Ore Hoppers":"矿石料斗扭亏为盈",
    "Part Bins":"零件仓",
    "Tunnel Exit ":"隧道出口同时维持五座熔炉燃烧。",
    "Assembler Speed":"组装机速度持续供给二十台组装机。",
    "Deep Bore":"深层钻探维持二十座熔炉运转。",
    "Drill Yield":"钻机产出铺设二十五格传送带。",
    "Filter Splitters":"过滤分流器铺设两百格传送带。",
    "Night Shift":"夜班大规模生产",
    "Battery Banks":"电池组传送带之上",
    "Deep Drill ":"深层钻机露天矿场",
    "Express Lanes":"高速通道同时拥有二十五级升级。",
    "Heat Exchanger":"热交换器放置四个分流器。",
    "Hub Logistics":"枢纽物流轧板厂",
    "Precision Tools":"精密工具板材盈余",
    "Requisition Rate":"申领速率分数达到十万。",
    "Trade Network":"贸易网络分数达到一千。",
    "Beacon ":"信标研究预算",
    "Research Lab ":"研究实验室同时运行五台组装机。",
    "Catalysts":"催化剂同时运行五座化工厂。",
    "Beacon Field":"信标场利用隧道，在同一设施下方运行四条产线。",
    "Beacon Tuning":"信标调谐工厂累计运行一小时。",
    " Milestones pay a small permanent bonus each, on top of the upgrade tree. Nothing is spent to earn one, and nothing takes one back. ":"里程碑每项都会提供少量永久加成，独立于升级树。达成无需消耗资源，且加成不会被收回。同时启用二十台采矿机。",
    "Bank a thousand iron plate.":"储备一千块铁板。冶炼产线",
    "Bank five hundred coal.":"储备五百煤炭。分拣办公室",
    "Bank five thousand iron plate at once.":"一次性储备五千块铁板。物资储备",
    "Bank two hundred and fifty circuits.":"储备两百五十个电路。同时开采五处矿点。",
    "Belt Baron":"传送带大亨组装",
    "Circuit City":"电路之城消耗",
    "Coal Cellar":"煤炭地窖物流",
    "Completionist":"全收集者采矿",
    "Conglomerate":"联合企业电力",
    "Cracking Plant":"裂解工厂重置视角",
    "Deliver a hundred iron plates a second, averaged over a full minute.":"一分钟平均每秒输送一百块铁板。出售升级等级可全额返还资源，不会因为购买升级导致存档卡死。",
    "Drill Team":"钻探小队冶炼",
    "Earn fifteen other achievements.":"解锁十五项其他成就。永久生效且作用于整个工厂，可全额折价回售",
    "Flow State":"流畅运转组装机速度",
    "Foundry":"铸造厂电池组",
    "Beacon Field ":"信标场",
    "Beacon Tuning ":"信标调谐",
    "Beacons ":"信标",
    "Belt Speed ":"传送带速度",
    "Catalysts ":"催化剂",
    "Conveyor Logic ":"传送带逻辑",
    "Deep Bore ":"深层钻探",
    "Drafting Office ":"制图室",
    "Drill Speed ":"钻机速度",
    "Drill Yield ":"钻机产出",
    "Electric Assembly ":"电力组装",
    "Electric Mining ":"电力开采",
    "Electric Smelting ":"电力冶炼",
    "Electrification ":"电气化",
    "Express Lanes ":"高速通道",
    "Factory upgrades":"工厂升级",
    "Filter Splitters ":"过滤分流器",
    "Firebox ":"燃烧室",
    "Fuel Efficiency ":"燃料效率",
    "Furnace Speed ":"熔炉速度",
    "Heat Exchanger ":"热交换器",
    "Hub Logistics ":"枢纽物流",
    "Land Survey ":"土地勘测",
    "Level":"等级",
    "Miners cycle faster.":"采矿机运转更快。",
    "Mining T1":"一级采矿",
    "Next level":"下一级",
    "Night Shift ":"夜班",
    "Ore Bins ":"矿石仓",
    "Ore Hoppers ":"矿石料斗",
    "Part Bins ":"零件仓",
    "Petrochemistry ":"石油化工",
    "Pole Reach ":"电线杆覆盖范围",
    "Precision Tools ":"精密工具",
    "Requisition Rate ":"申领速率",
    "Research Labs ":"研究实验室",
    "Trade Network ":"贸易网络",
    "drag to pan, pinch to zoom":"拖拽平移，双指缩放",
    "drag to pan, scroll to zoom":"拖拽平移，滚轮缩放",
    "Items travel further each tick.":"物品每帧移动距离更远。",
    " when unlocked":"解锁时",
    "Miners run faster the more belt you have laid.":"铺设的传送带越多，采矿机运转越快。",
    "Unlocks the splitter":"解锁分流器",
    "one lane in, three lanes out in turn.":"单入口，循环向三个出口输送物料。",
    "Smelting finishes sooner. Coal per smelt is unchanged.":"冶炼完成速度提升。单次冶炼煤炭消耗不变。",
    "Crafts finish sooner.":"制作完成速度提升。",
    " The book is closed. Buy ":"手册已关闭。",
    " in the upgrade tree to open it; every level after the first adds another page. ":"在升级树中购买解锁；每提升一级，新增一页内容。",
    "A stamp is charged like building by hand, lands only on surveyed ground, and places whatever fits":"印记放置的资源消耗和手动建造一致，仅可在已勘测的土地上使用，放置范围内可容纳的建筑会生成；",
    "what will not fit is reported instead of cancelling the rest.":"无法放置的内容会单独提示，其余建筑不会取消。",
    " - open a machine to set its recipe; drag still pans ":"- 点开机器设置配方；拖拽仍可平移视角",
    " - pan":"- 平移视角",
    " - pan, or right / middle drag":"- 平移视角，或右键/中键拖拽",
    " - pick a toolbar slot. Press the active one again, or ":"- 选中工具栏项目。再次点击当前选中项，或者",
    " - place; belts auto-connect along the drag":"- 放置建筑；拖拽时传送带自动连接",
    " - remove one building instantly, fully refunded; works with any tool selected ":"- 立即拆除单个建筑，全额返还资源；任意工具状态下均可使用",
    " - select an area, then confirm. Removal always refunds the full cost plus anything held inside ":"- 框选区域，随后确认。拆除将全额返还建造资源以及建筑内留存物资",
    " - the red wash is ground you have not surveyed. Buy Land Survey in the upgrade tree to double the square you can build on ":"- 红色区域代表未勘测土地。在升级树购买土地勘测，可将可建造区域扩大一倍",
    " - turn the building under the cursor; over bare ground it turns the ghost instead (":"- 旋转光标下的建筑；在空地时仅旋转预览虚影",
    " - zoom, ":"- 缩放视角",
    " Anonymous usage analytics are off, and nothing is stored for them. ":"匿名使用统计已关闭，不会留存相关数据。",
    " Miners dig ore, belts carry it, the Hub banks it. Everything below is optional. ":"采矿机开采矿石，传送带运送物资，枢纽负责存储。下方所有内容均为可选。",
    " Your save lives in this browser and there is no account. ":"存档保存在当前浏览器，无需账号。",
    " push out of their marked edge into the tile they face, and miners only sit on ore. Route anything into the Hub to bank it ":"从标记边缘推送物资至朝向地块，采矿机仅能放置在矿点上。将物资输送至枢纽即可存入仓库。",
    " puts it back ":"放回原位",
    " reverses) ":"反向运作",
    " takes from behind and sends items out left, ahead and right in turn; a merger does the reverse. Both are belts as far as upgrades care ":"从后方拾取物料，依次向左、向前、向右输出；合并器功能与之相反。在升级效果判定上，二者均视作传送带。",
    " turns the stamp, ":"旋转印记，",
    ", to drop back to inspect ":"回到查看模式",
    "- achievements":"- 成就",
    "- blueprints":"- 蓝图",
    "- copy the building under the cursor":"- 复制光标下的建筑",
    "- the recipe book":"- 配方手册",
    "- the upgrade tree":"- 升级树",
    "Build and remove":"建造与拆除",
    "Inspect + click":"查看 + 点击",
    "Land":"土地",
    "Machines":"机器",
    "Panels":"面板",
    "Power":"电力",
    "Privacy.":"隐私设置",
    "Shapes and ground":"地形与地块",
    "Shift+R":"Shift+R",
    "Tunnel":"隧道",
    "Turn analytics on":"开启统计分析",
    "Wheel":"滚轮",
    "drag an area to copy it into the book. A page in hand stamps on a click and still copies on a drag.":"框选区域，可将其复制到手册中。手持手册页面时，单击进行印记放置，拖拽依旧可以复制区域。",
    "facing and recipe come with it":"朝向与配方一并复制",
    "milestones that each pay a small permanent bonus, earned once and never lost":"里程碑：每项提供少量永久加成，达成一次即可获得，永久保留",
    "permanent, factory-wide bonuses bought with banked items, sellable back at full price":"使用储备物资购买的全局工厂永久加成，可全额回售",
    "what makes what, and out of what":"物品产出关系，以及所需原料",
    "· out":"· 输出",
    "Running":"运行中",
    "Output backed up":"已备份输出",
    " · carrying Iron Ore":"· 正在运输铁矿",
    " Makes ":"制作",
    " Smelts whatever it is fed - ":"熔炼喂入的任何物料 -",
    "Ore slots":"矿石槽位",
    "Out of fuel":"燃料耗尽",
    "carrying Iron Ore":"正在运输铁矿",
    " Assembly":"组装",
    " Cost":"消耗",
    " Logistics":"物流",
    " Mining":"采矿",
    " Recenter ":"重置视角",
    " Selling a level refunds its full price, so no purchase can strand a save. ":"出售升级等级可全额返还资源，不会因为购买升级导致存档卡死。",
    " Smelting":"冶炼",
    " permanent and factory wide, sellable back at full price ":"永久生效且作用于整个工厂，可全额折价回售",
    "One more page in the blueprint book per level. The first opens it.":"蓝图手册每升一级增加一页。第一级解锁手册。",
    "Everything delivered is worth more score.":"所有交付物的分数价值更高。",
    "Miners hold a bigger batch before they stall.":"采矿机在停工前可囤积更多批次。",
    "Each mining cycle pulls out a whole extra ore.":"每次采矿循环多开采一个矿石。",
    "Unlocks the electric miner":"解锁电动采矿机",
    "half again as fast, on charge.":"耗电，速度提升一半。",
    "Heavier drills":"重型钻机",
    "faster, and half an ore more per cycle.":"速度更快，每循环多产出半个矿石。",
    "Doubles the side of the buildable square around the hub.":"枢纽周围可建造区域扩大一倍。",
    "Every upgrade level you own makes deliveries worth a little more.":"你拥有的每一级升级，都会让交付物价值略微提升。",
    "A larger share of your online rate is paid while you are away.":"离线时按在线产出速率的更大比例结算收益。",
    "Unlocks coal generators, batteries and the poles that wire them.":"解锁燃煤发电机、电池以及连接它们的电线杆。",
    "Each generator makes half again as much charge, level on level.":"每级使发电机发电量提升一半，逐级叠加。",
    "x1.50 Coal Generator output":"x1.50 燃煤发电机产出",
    "Every battery holds twice the charge, each level over the last.":"每级使电池容量翻倍。",
    "x2.00 Battery capacity":"x2.00 电池容量",
    "Poles wire further, to each other and to what they gather.":"电线杆之间以及与所连接设备的连线距离更远。",
    "Furnaces stockpile more ore and more coal.":"熔炉囤积更多矿石和煤炭。",
    "Every fuel item burns longer, in every building that burns it.":"所有燃烧燃料的建筑，每个燃料物品燃烧时间更长。",
    "Furnaces share heat":"熔炉共享热量",
    "each one built speeds up all of them.":"每建造一座，其余所有熔炉都会加速。",
    "Unlocks the electric furnace":"解锁电炉",
    "half again as fast, on charge not coal.":"耗电而非燃煤，速度提升一半。",
    "A second speed track for assemblers, stacking with the first.":"为组装机增设第二条速度加成轨道，可与第一条叠加。",
    "Unlocks the electric assembler":"解锁电力组装机",
    "Assemblers hold more parts, so a slow feed stalls them less.":"组装机可容纳更多零件，进料不足时更不容易停工。",
    "Unlocks the chemical plant":"解锁化工厂",
    "coal into plastic, plastic into processors.":"煤炭转化为塑料，塑料转化为处理器。",
    "Unlocks the research lab":"解锁研究实验室",
    "turns a processor, a motor and plastic into a Research Core.":"将处理器、马达与塑料加工为研究核心。",
    "Chemical plants crack and craft faster.":"化工厂裂解与制作速度提升。",
    "Unlocks the beacon":"解锁信标",
    "every machine inside its radius runs faster.":"范围内所有机器运转提速。",
    "Each beacon in reach hands a machine a bigger share of speed.":"机器每受一个信标影响，获得更多速度加成。",
    "Beacons reach further, so their circles start to overlap.":"信标覆盖范围扩大，多个信标的作用区域开始重叠。",
    "Point a splitter output at one item. Everything else leaves by the outputs left open.":"将分流器的一个出口指定为单一物品。其余所有物品从其他开放出口送出。",
    "Belts move at a multiple of their base speed.":"传送带速度为基础速度的倍数。",
    "Unlocks the merger":"解锁合并器",
    "three lanes in, one lane out.":"三通道输入，单通道输出。",
    "Unlocks the puller":"解锁拉取器",
    "lifts a chosen item out of your bank onto a belt.":"从仓库提取指定物品放到传送带上。",
    "Unlocks the pusher":"解锁推送器",
    "a second hub, banking whatever is belted into it.":"第二个枢纽，存入所有输送至此的物资。",
    "Pullers lift items out of the bank faster.":"拉取器从仓库提取物品的速度提升。",
    "Unlocks both ends of a tunnel, for running a lane under a line.":"解锁隧道入口与出口，可让一条物料通道从另一产线下方穿过。",
    "offline rate ":"离线效率 ",
    "In effect: ":"生效中：",
    " · carrying Coal":"· 运输煤",
    " · carrying Copper Ore":"· 运输铜矿石",
    " · carrying Copper Plate":"· 运输铜板",
    " · carrying Iron Plate":"· 运输铁板",
    "carrying Copper Plate":"· 运输铜板",
    "Idle":"空闲",
    "Going Underground":"深入地下",
    "Have a hundred machines running.":"同时运行一百台机器。",
    "Hold fifty score per second across a full minute.":"一分钟内保持每秒获得五十点分数。",
    "In The Black":"扭亏为盈",
    "Industrialist":"工业家",
    "Keep five furnaces lit at once.":"同时维持五座熔炉燃烧。",
    "Keep twenty assemblers fed.":"持续供给二十台组装机。",
    "Keep twenty furnaces burning.":"维持二十座熔炉运转。",
    "Lay twenty five belt tiles.":"铺设二十五格传送带。",
    "Lay two hundred belt tiles.":"铺设两百格传送带。",
    "Mass Production":"大规模生产",
    "On The Belt":"传送带之上",
    "Open Pit":"露天矿场",
    "Own twenty five upgrade levels at once.":"同时拥有二十五级升级。",
    "Place four splitters.":"放置四个分流器。",
    "Plate Mill":"轧板厂",
    "Plate Surplus":"板材盈余",
    "Reach a score of one hundred thousand.":"分数达到十万。",
    "Reach a score of one thousand.":"分数达到一千。",
    "Research Budget":"研究预算",
    "Run five assemblers at once.":"同时运行五台组装机。",
    "Run five chemical plants at once.":"同时运行五座化工厂。",
    "Run four lines under something with tunnels.":"利用隧道在设施下方运行四条产线。",
    "Run the factory for an hour of uptime.":"工厂累计运行一小时。",
    "Run twenty miners at once.":"同时启用二十台采矿机。",
    "Smelting Line":"冶炼产线",
    "Sorting Office":"分拣办公室",
    "Stockpile":"物资储备",
    "Work five ore patches at once.":"同时开采五处矿点。",
    "earned":"已获取",
    " Sell ":"出售",
    "Electric Furnace speed ":"电炉速度",
    "Installed":"已安装",
    "carrying Coal":"正在运输煤炭",
    " Achievement ":"成就",
    "item value ":"物品价值",
    "Merger speed ":"合并器速度",
    "Splitter speed ":"分流器速度",
    "Tunnel Entry speed ":"隧道入口速度",
    "Tunnel Exit speed ":"隧道出口速度",
    "Not enough resources to place Assembler.":"资源不足，无法放置组装机。",
    "Assemble something":"组装物品",
    "Open the Assembler slot (4) and pick a recipe with more than one input, like a Gear.":"打开组装机工具栏（快捷键4），选择一项需要多种原料的配方，例如齿轮。",
    " Back to current step ":"返回当前步骤",
    "Look inside":"查看详情",
    "Switch to Inspect (Esc, or click the Inspect tool) and click the furnace. Its panel shows the recipe running and whether it is actually working.":"切换至查看模式（Esc键，或点击查看工具），点击熔炉。面板会显示正在执行的配方以及设备运行状态。",
    "In the way? Right click a tile to remove it, or use the Bulldoze tool for an area.":"挡住了？右键地块拆除，或使用拆除工具框选区域。",
    "Open the Furnace slot (3) and place one downstream of the ore. Feed it coal too, it burns fuel to run.":"打开熔炉工具栏（快捷键3），在矿点下游放置一座熔炉。同时供给煤炭，熔炉需要消耗燃料才能运作。",
    "Smelt it":"冶炼物资",
    "Bank it":"存入仓库",
    "Pick the Belt tool (1) and drag from the miner to the Hub. Anything that reaches it banks itself.":"选择传送带工具（快捷键1），从采矿机拖拽至枢纽。物资输送到枢纽后会自动存入仓库。",
    "Copy a setup":"复制布局",
    "Hover a machine and press Q. It arms the same building, recipe and facing as the tool in hand, so the next one you place is already configured.":"鼠标悬停在机器上并按下Q键。工具会复制该建筑、配方与朝向，后续放置的建筑将沿用这套配置。",
    "Open the Upgrade tree (U) and buy the first level of anything.":"打开升级树（快捷键U），购买任意一项的一级升级。",
    "Spend on upgrades":"投入升级",
    "Not unlocked yet.":"尚未解锁。",
    "Open the Belt slot (1), tap the small triangle to see the rest of it, and place a Splitter to send one belt two ways.":"打开传送带工具栏（快捷键1），点击小三角展开更多选项，放置分流器，将一条传送带分为两路。",
    "Split a line":"分流产线",
    "Open the Power slot (5), find the Generator in it, and place it and a Pole in reach of each other to run electric machines.":"打开电力工具栏（快捷键5），找到发电机，将发电机与电线杆放置在互相可达范围内，为电动设备供电。",
    "Wire power":"接通电力",
    "Close the loop":"构建循环",
    "Open the Belt slot (1) again, find the Puller in it, and place one to lift a banked item back onto a belt and feed it into something new.":"再次打开传送带工具栏（快捷键1），找到拉取器并放置，从仓库提取物资放回传送带，供给新设备。",
    " Paste a backup, or open the file you saved. This replaces the factory you are playing now, and that is the one thing in this game you cannot undo, so take a copy above first if there is anything here worth keeping. ":"粘贴备份，或打开已保存的文件。该操作会覆盖当前正在游玩的工厂，这是本游戏唯一无法撤销的操作。如果当前存档有需要保留的内容，请先复制一份。",
    "clearing site data does it, private windows never keep anything, and a phone that has not seen the site for a week may do it on its own. Keep a copy of the text below and nothing is ever lost. Adding the game to your home screen makes it far less likely in the first place.":"清除网站数据会导致存档丢失，无痕窗口不会保存任何内容；手机若一周未访问该页面，存档也可能自动清除。请保存下方文本备份，这样就不会丢失进度。将游戏添加到主屏幕，可大幅降低存档丢失的概率。",
    " Open a file ":"打开文件",
    " Save to a file ":"保存至文件",
    " a backup that outlives the browser ":"可脱离浏览器留存的备份",
    "Back it up":"备份存档",
    "Load this save":"读取此存档",
    "Restore one":"恢复存档",
    "The game saves itself in this browser, and a browser is allowed to throw that away":"游戏将进度保存在当前浏览器内，浏览器有可能清除这份存档数据。",
    "Deep Drill speed ":"深层钻机速度",
    "Electric Miner speed ":"电动采矿机速度",
    "Miner speed ":"采矿机速度",
    "Waiting for input":"等待输入",
    "Cancel":"取消",
    "Start again?":"重新开始？",
    "This wipes the save and generates a new map. Everything built, banked, bought and earned goes with it.":"该操作会清空存档并生成新地图。所有建造物、库存物资、购买升级与成就全部清除。",
    "Wipe it":"确认清空",
    " Recipe ":" 配方 ",
    " Clear ":" 清除 ",
    " Paid from your factory's average output of 26.95 score/sec over the last minute of play, at 50% while away. Build a wider base and the rate carries over next time. ":"依据游戏过去一分钟工厂平均产出26.95分数/秒计算离线收益，离线结算比例为50%。扩建工厂规模，下次上线时产出速率可延续生效。",
    "Assembler buffer size ":"组装机缓存容量",
    "Electric Assembler buffer size ":"电力组装机缓存容量",
    "Electric Assembler speed ":"电力组装机速度",
    "Electric Furnace buffer size ":"电炉缓存容量",
    "Furnace buffer size ":"熔炉缓存容量",
    "fuel burn time ":"燃料燃烧时长",
    "Input buffer":"输入缓存",
    "Load it":"载入",
    "Load this save?":"是否载入此存档？",
    "The factory you are playing now is replaced by the one in the text. Everything built, banked, bought and earned here goes with it.":"你当前正在游玩的工厂将会被文本内的存档覆盖。你在此处建造、储存、购买以及获得的所有内容都会被清除。",
    " Offline earnings cap at 8h, so 8h was paid. ":"离线收益上限为8小时，本次已按8小时结算。",
    "Right":"右键",
    "Left":"左键",
    "Bank":"存储",
    " Close ":" 关闭 ",
    " Outputs ":" 输出 ",
    "not running":"未运行",
    "Not on a network":"无网络",
    "Ahead":"前进",
    "Anything else":"其他选项",
    " Recenter on Hub ":"以中心枢纽为视角重置",
    " Nothing copied yet. With the Blueprint tool selected, drag a rectangle around a piece of factory to copy it, recipes and facings included. ":"尚未复制任何内容。选中蓝图工具，框选一片工厂区域即可复制，包含配方与朝向。",
    " Replay from the start ":"从头重放",
    "Every step is done. The factory is yours from here.":"全部教程已完成。工厂交由你自由运营。",
    "Battery capacity ":"电池容量",
    "Battery speed ":"电池充放速度",
    "Battery unlocked ":"电池 已解锁",
    "Beacon speed ":"信标速度",
    "Chemical Plant speed ":"化工厂速度",
    "Coal Generator output ":"煤炭发电机输出",
    "Coal Generator speed ":"煤炭发电机速度",
    "Coal Generator unlocked ":"煤炭发电机 已解锁",
    "Deep Drill buffer size ":"深层钻机缓存容量",
    "Deep Drill yield ":"深层钻机产出",
    "Electric Assembler unlocked ":"电力组装机 已解锁",
    "Electric Furnace unlocked ":"电力熔炉 已解锁",
    "Electric Miner buffer size ":"电力采矿机缓存容量",
    "Electric Miner unlocked ":"电力采矿机 已解锁",
    "Electric Miner yield ":"电力采矿机产量",
    "Empty speed ":"空载速度",
    "Hub speed ":"中心枢纽速度",
    "Merger unlocked ":"合并器 已解锁",
    "Miner buffer size ":"采矿机缓存容量",
    "Miner yield ":"采矿机产出",
    "Power Pole radius ":"电线杆覆盖范围",
    "Power Pole speed ":"电线杆架设速度",
    "Power Pole unlocked ":"电线杆 已解锁",
    "Puller speed ":"抽取器速度",
    "Puller unlocked ":"抽取器 已解锁",
    "Pusher speed ":"推送器速度",
    "Research Lab speed ":"研究实验室速度",
    "Splitter filter slots ":"分离器过滤槽位",
    "Splitter unlocked ":"分离器 已解锁",
    "Tunnel Entry unlocked ":"隧道入口 已解锁",
    "Tunnel Exit unlocked ":"隧道出口 已解锁",
    "blueprint slots ":"蓝图槽位",
    "buildable land ":"可建造区域",
    "Fully upgraded.":"已满级。",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "关注新公众号": "关注新公众号",
    "打开微信扫一扫": "打开微信扫一扫",
    "游戏攻略交流论坛": "游戏攻略交流论坛",
    "点击加群": "点击加群",
    "锅巴汉化": "锅巴汉化",
    "WASD": "WASD",
    " (E)": " (E)",
    "Esc": "Esc",
    " (S)": " (S)",
    " (W)": " (W)",
    " (N)": " (N)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "x": "x",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    
};
// ============================================================
// cnResourceNames — 资源名词翻译（备用，优先级低于 cnItems）
// ============================================================
// 支持 "名词: 数值" 格式的自动翻译（如 "Mana: 500" → "法力：500"）
var cnResourceNames = {};
// cnRegReplace — 正则替换（备用，优先级低于精确匹配但高于模板/分类）
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^ Paid from your factory\'s average output of (.+) score\/sec over the last minute of play, at (.+) while away. Build a wider base and the rate carries over next time. $/, '根据游戏最近一分钟工厂平均产出 $1 分数/秒计算离线收益，离线结算比例为$2。扩建工厂规模，下次上线时产出速率可延续生效。'],
    [/^ Away (.+) min. $/, ' 离开了 $1 分钟。'],
    [/^ Objective (.+)$/, ' 目标 $1 '],
    [/^ Away (.+). $/, ' 离开了 $1。 '],
    [/^(.+) ticks played$/, '进行游戏 $1 tick'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^\+([\d\.]+)\/s$/, '+$1\/秒'],
    [/^\-([\d\.]+)\/s $/, '-$1\/秒 '],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)s$/, '$1秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^have ([\d\.]+)(.+)$/, '拥有 $1$2'],
    [/^Chemical Plant · ([\d\.]+)s$/, '化工厂 · $1 秒'],
    [/^Research Lab · ([\d\.]+)s$/, '研究实验室 · $1 秒'],
    [/^Assembler · ([\d\.]+)s$/, '组装机 · $1 秒'],
    [/^Assembler · ([\d\.]+)ms$/, '组装机 · $1 ms'],
    [/^Furnace · ([\d\.]+)s$/, '熔炉 · $1 秒'],
    [/^Furnace · ([\d\.]+)ms$/, '熔炉 · $1 ms'],
    [/^ \+([\d\.]+)\/s $/, ' +$1/秒 '],
    [/^\+([\d\.]+)\% Splitter unlocked$/, '+$1% 分流器 解锁'],
    [/^\+([\d\.]+)\% speed$/, '+$1% 速度'],
    [/^\+([\d\.]+)\% Miner speed$/, '+$1% 采矿机 速度'],
    [/^\+([\d\.]+)\% Furnace speed$/, '+$1% 熔炉 速度'],
    [/^\+([\d\.]+)\% Belt speed$/, '+$1% 传送带 速度'],
    [/^\+([\d\.]+)\% Puller speed$/, '+$1% 拉取器 速度'],
    [/^\+([\d\.]+)\% Splitter filter slots$/, '+$1% 分离器过滤槽'],
    [/^\+([\d\.]+)\% Research Lab unlocked$/, '+$1% 研究实验室 解锁'],
    [/^\+([\d\.]+)\% Beacon radius$/, '+$1% 信标 半径'],
    [/^\+([\d\.]+)\% Power Pole radius$/, '+$1% 电线杆 半径'],
    [/^\+([\d\.]+)\% blueprint slots$/, '+$1% 蓝图槽位'],
    [/^\+([\d\.]+)\% Beacon boost$/, '+$1% 信标 提升'],
    [/^\+([\d\.]+)\% Furnace buffer size$/, '+$1% 熔炉 缓冲区大小'],
    [/^\+([\d\.]+)\% Miner buffer size$/, '+$1% 采矿机 缓冲区大小'],
    [/^\+([\d\.]+)\% Assembler buffer size$/, '+$1% 组装机 缓冲区大小'],
    [/^\+([\d\.]+)\% Tunnel Entry unlocked$/, '+$1% 隧道入口 解锁'],
    [/^\+([\d\.]+)\% Tunnel Exit unlocked$/, '+$1% 隧道出口 解锁'],
    [/^\+([\d\.]+)\% Electric Assembler unlocked$/, '+$1% 电动组装机 解锁'],
    [/^\+([\d\.]+)\% Chemical Plant unlocked$/, '+$1% 化工厂 解锁'],
    [/^\+([\d\.]+)\% Electric Furnace unlocked$/, '+$1% 燃煤发电机 解锁'],
    [/^\+([\d\.]+)\% Coal Generator unlocked$/, '+$1% 电池 解锁'],
    [/^\+([\d\.]+)\% Power Pole unlocked$/, '+$1% 电线杆 解锁'],
    [/^\+([\d\.]+)\% Electric Miner unlocked$/, '+$1% 电动采矿机 解锁'],
    [/^\+([\d\.]+)\% Battery unlocked$/, '+$1% 电池 解锁'],
    [/^\+([\d\.]+)\% Puller unlocked$/, '+$1% 拉取器 解锁'],
    [/^\+([\d\.]+)\% Beacon unlocked$/, '+$1% 信标 解锁'],
    [/^\+([\d\.]+)\% Merger unlocked$/, '+$1% 合并器 解锁'],
    [/^\+([\d\.]+)\% Pusher unlocked$/, '+$1% 推送器 解锁'],
    [/^\+([\d\.]+)\% Miner yield$/, '+$1% 采矿机 产出'],
    [/^\+([\d\.]+)\% Miner speed$/, '+$1% 采矿机 速度'],
    [/^\+([\d\.]+)\% Chemical Plant speed$/, '+$1% 化工厂 速度'],
    [/^\+([\d\.]+)\% Assembler speed$/, '+$1% 组装机 速度'],
    [/^\+([\d\.]+)\% fuel burn time$/, '+$1% 燃料燃烧时间'],
    [/^\+([\d\.]+)\% offline rate$/, '+$1% 离线效率'],
    [/^\+([\d\.]+)\% item value$/, '+$1% 物品价值'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Furnace speed per Furnace, max \+([\d\.]+)\%$/, '每座熔炉提升熔炉速度 +$1%，最高 +$2%'],
    [/^\+([\d\.]+)\% Miner speed per Belt, max \+([\d\.]+)\%$/, '每条传送带提升采矿机速度 +$1%，最高 +$2%'],
    [/^\+([\d\.]+)\% item value per upgrade level owned, max \+([\d\.]+)\%$/, '每拥有一级升级，物品价值 +$1%，最高 +$2%'],
    [/^x([\d\.]+) buildable land$/, 'x$1 可建造土地'],
    [/^x([\d\.]+) Coal Generator output$/, 'x$1 燃煤发动机输出'],
    [/^x([\d\.]+) Battery capacity$/, 'x$1 电池容量'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^ · pull-coal ([\d\.]+)\% \(([\d\.]+)ms left\)$/, '· 运煤 $1% ($2ms 剩余)'],
    [/^ · pull-iron-ore ([\d\.]+)\% \(([\d\.]+)ms left\)$/, '· 运铁矿石 $1% ($2ms 剩余)'],
    [/^ · gear ([\d\.]+)\% \(([\d\.]+)ms left\)$/, '· 齿轮 $1% ($2ms 剩余)'],
    [/^ · gear ([\d\.]+)\% \(([\d\.]+)s left\)$/, '· 齿轮 $1% ($2秒 剩余)'],
    [/^· gear ([\d\.]+)\% \(([\d\.]+)ms left\) \| in$/, '· 齿轮 $1% ($2ms 剩余) \| 在'],
    [/^· circuit ([\d\.]+)\% \(([\d\.]+)s left\) \| in$/, '· 电路 $1% ($2秒 剩余) \| 在'],
    [/^· circuit ([\d\.]+)\% \(([\d\.]+)ms left\) \| in$/, '· 电路 $1% ($2ms 剩余) \| 在'],
    [/^· iron-plate ([\d\.]+)\% \(([\d\.]+)s left\)$/, '· 铁板 $1% ($2秒 剩余)'],
    [/^· iron-plate ([\d\.]+)\% \(([\d\.]+)s left\) \| in$/, '· 铁板 $1% ($2秒 剩余) | 在'],
    [/^· iron-plate ([\d\.]+)\% \(([\d\.]+)ms left\) \| in$/, '· 铁板 $1% ($2ms 剩余) | 在'],
    [/^· copper-plate ([\d\.]+)\% \(([\d\.]+)s left\) \| in$/, '· 铜板 $1% ($2秒 剩余) | 在'],
    [/^· copper-plate ([\d\.]+)\% \(([\d\.]+)ms left\) \| in$/, '· 铜板 $1% ($2ms 剩余) | 在'],
    [/^([\d\.,]+)s left$/, '$1秒 剩余'],
    [/^([\d\.,]+)ms left$/, '$1ms 剩余'],
    [/^([\d\.,]+) score$/, '$1 分数'],
    [/^([\d\.,]+) Iron Plate$/, '$1 铁板'],
    [/^([\d\.,]+) Iron Plate, ([\d\.,]+) Gear$/, '$1 铁板, $2 齿轮'],
    [/^([\d\.,]+) Iron Plate, ([\d\.,]+) Gear, ([\d\.,]+) Steel$/, '$1 铁板, $2 齿轮, $3 钢'],
    [/^([\d\.,]+) Iron Plate, ([\d\.,]+) Circuit, ([\d\.,]+) Steel$/, '$1 铁板, $2 电路, $3 钢'],
    [/^([\d\.,]+) Iron Plate, ([\d\.,]+) Gear, ([\d\.,]+) Circuit$/, '$1 铁板, $2 齿轮, $3 电路'],
    [/^([\d\.,]+) Iron Plate, ([\d\.,]+) Gear, ([\d\.,]+) Circuit, ([\d\.,]+) Steel$/, '$1 铁板, $2 齿轮, $3 电路, $4 钢'],
    [/^([\d\.,]+) Furnace placed$/, '放置 $1 熔炉'],
    [/^([\d\.,]+) Tunnel Entry placed$/, '放置 $1 隧道入口'],
    [/^([\d\.,]+) Assembler placed$/, '放置 $1 组装机'],
    [/^([\d\.,]+) Belt placed$/, '放置 $1 传送带'],
    [/^([\d\.,]+) machines placed$/, '放置 $1 机器'],
    [/^([\d\.,]+) Splitter placed$/, '放置 $1 分流器'],
    [/^([\d\.,]+) Miner placed$/, '放置 $1 采矿机'],
    [/^([\d\.,]+) Chemical Plant placed$/, '放置 $1 化工厂'],
    [/^([\d\.,]+) Coal banked$/, '存储 $1 煤'],
    [/^([\d\.,]+) Circuit banked$/, '存储 $1 电路'],
    [/^([\d\.,]+) Iron Plate banked$/, '存储 $1 铁板'],
    [/^([\d\.,]+) Iron Plate per second$/, '每秒 $1 铁板'],
    [/^([\d\.,]+) score per second$/, '每秒 $1 分'],
    [/^([\d\.,]+) achievements earned$/, '解锁 $1 成就'],
    [/^([\d\.,]+) upgrade levels owned$/, '拥有 $1 升级等级'],
    [/^([\d\.,]+) Research Core$/, '$1 研究核心'],
    [/^([\d\.,]+) Circuit$/, '$1 电路'],
    [/^([\d\.,]+) Titanium Ore$/, '$1 钛矿石'],
    [/^([\d\.,]+) Copper Ore$/, '$1 铜矿石'],
    [/^([\d\.,]+) Iron Ore$/, '$1 铁矿石'],
    [/^([\d\.,]+) Copper Plate$/, '$1 铜板'],
    [/^([\d\.,]+) Iron Plate$/, '$1 铁板'],
    [/^([\d\.,]+) Titanium Plate$/, '$1 钛板'],
    [/^([\d\.,]+) Plastic$/, '$1 塑料'],
    [/^([\d\.,]+) Coal$/, '$1 煤'],
    [/^([\d\.,]+) Steel$/, '$1 钢'],
    [/^([\d\.,]+) Motor$/, '$1 马达'],
    [/^([\d\.,]+) Gear$/, '$1 齿轮'],
    [/^([\d\.,]+) Processor$/, '$1 处理器'],
    [/^([\d\.,]+) Plastic$/, '$1 塑料'],
    [/^([\d\.,]+) lv $/, '$1 等级 '],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Bank → ([\d\.,]+) Iron Ore$/, '存储 → $1 铁矿石'],
    [/^Bank → ([\d\.,]+) Coal$/, '存储 → $1 煤'],
    [/^([\d\.,]+) Iron Ore → ([\d\.,]+) Iron Plate$/, '$1 铁矿石 → $2 铁板'],
    [/^([\d\.,]+) Copper Ore → ([\d\.,]+) Copper Plate$/, '$1 铜矿石 → $2 铜板'],
    [/^([\d\.,]+) Iron Plate → ([\d\.,]+) Gear$/, '$1 铁板 → $2 齿轮'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Coal Generator$/, '$1 \/ $2 燃煤发动机'],
    [/^([\d\.,]+) \/ ([\d\.,]+) filtered $/, '$1 \/ $2 已过滤'],
    [/^([\d\.,]+) \/ ([\d\.,]+) score$/, '$1 \/ $2 分数'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Iron Plate banked$/, '存储 $1 \/ $2 铁板'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Gear banked$/, '存储 $1 \/ $2 齿轮'],
    [/^([\d\.,]+) \/ ([\d\.,]+) upgrade levels owned$/, '拥有 $1 \/ $2 升级等级'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Puller placed$/, '放置 $1 \/ $2 拉取器'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Splitter placed$/, '放置 $1 \/ $2 分流器'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Miner placed$/, '放置 $1 \/ $2 采矿机'],
    [/^saved ([\d\.,]+)s$/, '已保存 $1秒'],
    [/^saved ([\d\.,]+)m$/, '已保存 $1分'],
    [/^levels ([\d\.,]+)\-([\d\.,]+)$/, '等级 $1-$2'],
    [/^ Install level ([\d\.,]+)$/, ' 安装等级 $1'],
    [/^Coal x([\d\.,]+)$/, '煤 x$1'],
    [/^Copper Ore x([\d\.,]+)$/, '铜矿石 x$1'],
    [/^Copper Plate x([\d\.,]+)$/, '铜板 x$1'],
    [/^Iron Plate x([\d\.,]+)$/, '铁板 x$1'],
    [/^Iron Ore x([\d\.,]+)$/, '铁矿石 x$1'],
    [/^Iron Ore x([\d\.,]+), Iron Plate x([\d\.,]+)$/, '铁矿石 x$1, 铁板 x$2'],
    [/^Iron Plate x([\d\.,]+), Copper Plate x([\d\.,]+)$/, '铁板 x$1, 铜板 x$2'],
    [/^Iron Ore x([\d\.,]+), Coal x([\d\.,]+)$/, '铁矿石 x$1, 煤 x$2'],
    [/^Iron Ore x([\d\.,]+), Coal x([\d\.,]+) | out$/, '铁矿石 x$1, 煤 x$2 | 输出'],
    [/^Iron Ore x([\d\.,]+), Coal x([\d\.,]+), Iron Plate x([\d\.,]+)$/, '铁矿石 x$1, 煤 x$2, 铁板 x$3'],
    [/^Iron Ore x([\d\.,]+), Coal x([\d\.,]+), Iron Plate x([\d\.,]+) | out$/, '铁矿石 x$1, 煤 x$2, 铁板 x$3 | 输出'],
    [/^Copper Ore x([\d\.,]+), Coal x([\d\.,]+)$/, '铜矿石 x$1, 煤 x$2'],
    [/^have ([\d\.,]+)$/, '拥有 $1'],
    [/^Belt Speed ([\d\.,]+)$/, '传送带 速度 $1'],
    [/^Mining T([\d\.,]+)$/, '采矿 T$1'],
    [/^Assembly T([\d\.,]+)$/, '装配 T$1'],
    [/^Smelting T([\d\.,]+)$/, '冶炼 T$1'],
    [/^Hub T([\d\.,]+)$/, '枢纽 T$1'],
    [/^Chemistry T([\d\.,]+)$/, '化学 T$1'],
    [/^Power T([\d\.,]+)$/, '电力 T$1'],
    [/^Logistics T([\d\.,]+)$/, '物流 T$1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Conveyor Logic ([\d\.,]+)$/, '传送带逻辑 $1'],
    [/^Beacons ([\d\.,]+)$/, '信标 $1'],
    [/^Splitters ([\d\.,]+)$/, '分流器 $1'],
    [/^Pullers ([\d\.,]+)$/, '拉取器 $1'],
    [/^Catalysts ([\d\.,]+)$/, '催化剂 $1'],
    [/^Petrochemistry ([\d\.,]+)$/, '石油化工 $1'],
    [/^Electric Assembly ([\d\.,]+)$/, '电力组装 $1'],
    [/^Part Bins ([\d\.,]+)$/, '零件仓 $1'],
    [/^Ore Bins ([\d\.,]+)$/, '矿石仓 $1'],
    [/^Fuel Efficiency ([\d\.,]+)$/, '燃料效率 $1'],
    [/^Mergers ([\d\.,]+)$/, '合并器 $1'],
    [/^Drill Yield ([\d\.,]+)$/, '钻机产出 $1'],
    [/^Drill Speed ([\d\.,]+)$/, '钻机速度 $1'],
    [/^Ore Hoppers ([\d\.,]+)$/, '矿石料斗 $1'],
    [/^Hub Logistics ([\d\.,]+)$/, '枢纽物流 $1'],
    [/^Electrification ([\d\.,]+)$/, '电气化 $1'],
    [/^Assembler Speed ([\d\.,]+)$/, '组装机速度 $1'],
    [/^Furnace Speed ([\d\.,]+)$/, '熔炉速度 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Step (.+) of (.+)$/, '步骤 $1 \/ $2'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
]);
// 前缀/后缀提取（备用）
var cnPrefix = {
    ": ": "： ",
};
var cnPostfix = {
    ":": "：",
};
// 排除规则
var cnExcludeWhole = [
    /^([\d\.]+)KB $/,
    /^([\d\.]+)ms$/,
    /^\/ ([\d\.]+)ms$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^ \+([\d\.]+)K$/,
    /^ \+([\d\.]+)M$/,
    /^ \+([\d\.]+)B$/,
    /^ \+([\d\.]+)T$/,
    /^x([\d\.]+)$/,
    /^([\d\.]+) fps$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
];
var cnExcludePostfix = [];
